/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_lguplus_mucloud_CPCProperty */

#ifndef _Included_kr_co_lguplus_mucloud_CPCProperty
#define _Included_kr_co_lguplus_mucloud_CPCProperty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_co_lguplus_mucloud_CPCProperty
 * Method:    getHost
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_lguplus_mucloud_CPCProperty_getHost
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_lguplus_mucloud_CPCProperty
 * Method:    getUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_lguplus_mucloud_CPCProperty_getUrl
  (JNIEnv *, jclass);

/*
 * Class:     kr_co_lguplus_mucloud_CPCProperty
 * Method:    getCustCd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_lguplus_mucloud_CPCProperty_getCustCd
  (JNIEnv *, jclass);

/*
 * Class:     kr_co_lguplus_mucloud_CPCProperty
 * Method:    getInterfaceUrl
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_lguplus_mucloud_CPCProperty_getInterfaceUrl
  (JNIEnv *, jclass, jint);

/*
 * Class:     kr_co_lguplus_mucloud_CPCProperty
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_lguplus_mucloud_CPCProperty_getKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
